application: myjournal-me
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: journal.app

libraries:
- name: jinja2
  version: latest
- name: markupsafe                                                              
  version: latest
- name: webapp2
  version: "2.5.1"